# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import math
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np
import slangpy as spy
from neuralnetworks import IModel, SlangType
from util.math_helpers import udim_offset

from .texture import Texture

if TYPE_CHECKING:
    from datagen import (
        DataGenerators,
        FalcorBsdfDataGenerator,
        ReferenceMaterial,
        ReferenceMaterials,
    )

    from .encoder import Encoder


class LatentTexture(IModel):
    """Store the spatial neural material representation across materials.

    A texture exists for every material/UDIM/mip combination. Its texels are
    either optimized directly or generated by the trained material encoder.
    """

    @classmethod
    def from_reference_materials(
        cls,
        reference_materials: ReferenceMaterials,
        num_mip_levels: int,
        num_channels: int,
        optimizable: bool = True,
    ) -> LatentTexture:
        tex = LatentTexture(
            num_mip_levels,
            num_channels,
            optimizable,
        )

        # Material IDs are external indices and need not be dense. Allocate by
        # the largest ID because shaders index these tables directly by ID.
        num_materials = max(reference_materials.ids) + 1
        udim_stride = 100
        tex.tile_indirection = [0] * udim_stride * num_materials
        tex.material_texture_resolution = [0] * num_materials
        tex.material_texture_wrap = [True] * num_materials
        for material in reference_materials:
            id = material.id
            tex.num_tiles += len(material.udims)
            tex.material_ids.append(id)
            tex.has_udims[id] = material.has_udims
            tex.udim_mapping[id] = material.udims
            tex.material_texture_resolution[id] = material.texture_resolution
            tex.material_texture_wrap[id] = material.texture_wrap
        return tex

    @classmethod
    def from_material_ids(
        cls,
        material_ids: list[int],
        num_mip_levels: int,
        num_channels: int,
        resolution: int,
        wrap: bool,
        optimizable: bool = True,
        downscale_mips: bool = True,
    ) -> LatentTexture:
        tex = LatentTexture(
            num_mip_levels,
            num_channels,
            optimizable,
            downscale_mips,
        )

        # Keep the same layout as ``from_reference_materials()`` so a
        # model constructed without reference assets has identical shader data.
        num_materials = max(material_ids) + 1
        udim_stride = 100
        tex.tile_indirection = [0] * udim_stride * num_materials
        tex.material_texture_resolution = [0] * num_materials
        tex.material_texture_wrap = [True] * num_materials
        for id in material_ids:
            tex.num_tiles += 1
            tex.material_ids.append(id)
            tex.has_udims[id] = False
            tex.udim_mapping[id] = [1001]
            tex.material_texture_resolution[id] = resolution
            tex.material_texture_wrap[id] = wrap
        return tex

    def __init__(
        self,
        num_mip_levels: int,
        num_channels: int,
        optimizable: bool = True,
        downscale_mips: bool = True,
    ):
        super().__init__()

        self.num_mip_levels = num_mip_levels
        self.num_channels = num_channels
        self.optimizable = optimizable
        self.downscale_mips = downscale_mips

        self.num_tiles = 0
        self.material_ids: list[int] = []
        self.has_udims: dict[int, bool] = {}
        self.udim_mapping: dict[int, list[int]] = {}
        self.tile_indirection: list[int] = []
        self.material_texture_resolution: list[int] = []
        self.material_texture_wrap: list[bool] = []

    def model_init(self, module: spy.Module, input_type: SlangType):
        # Nested textures (for material IDs, UDIMs and MIP levels) are stored in
        # a flat 1D array.
        self.textures: list[Texture] = []

        # Initialize actual buffers.
        # Iteration order defines the ABI between ``tile_indirection`` and
        # textures. Each tile owns ``NumMipLevels`` consecutive entries.
        tile_idx = 0
        for material_id, udims in self.udim_mapping.items():
            for udim_id in udims:
                udim_idx = udim_id - 1001
                # The shader converts the two-digit UDIM coordinates to [0, 99],
                # hence the fixed 100-entry table for every material.
                udim_stride = 100
                self.tile_indirection[material_id * udim_stride + udim_idx] = tile_idx
                tile_idx += 1

                for mip_level in range(self.num_mip_levels):
                    tex = Texture(
                        device=module.device,
                        num_channels=self.num_channels,
                        resolution=self.resolution(material_id, mip_level),
                        wrap=self.wrap(material_id),
                        optimizable=self.optimizable,
                    )
                    self.textures.append(tex)

        self.tile_indirection_gpu = spy.Tensor.from_numpy(
            module.device, np.array(self.tile_indirection, dtype=np.int32)
        )
        self.material_texture_wrap_gpu = spy.Tensor.from_numpy(
            module.device, np.array(self.material_texture_wrap, dtype=np.int32)
        )
        self.module = module

    def make_optimizable(self) -> None:
        if self.optimizable:
            return
        self.optimizable = True
        for i in range(len(self.textures)):
            self.textures[i].make_optimizable()

    def texture(self, material_id: int, udim_id: int, mip_level: int) -> Texture:
        idx = self._texture_idx(material_id, udim_id, mip_level)
        return self.textures[idx]

    def _texture_idx(self, material_id: int, udim_id: int, mip_level: int):
        udim_stride = 100
        udim_idx = udim_id - 1001
        tile_idx = self.tile_indirection[material_id * udim_stride + udim_idx]
        return tile_idx * self.num_mip_levels + mip_level

    def resolution(self, material_id: int, mip_level: int) -> int:
        base_resolution = self.material_texture_resolution[material_id]
        if not self.downscale_mips:
            return max(1, base_resolution)
        return max(1, base_resolution >> mip_level)

    def wrap(self, material_id: int) -> bool:
        return self.material_texture_wrap[material_id]

    def to_numpy(
        self,
        material_id: int,
        udim_id: int,
        mip_level: int,
    ) -> np.ndarray:
        return self.texture(material_id, udim_id, mip_level).to_numpy()

    def from_numpy(
        self, material_id: int, udim_id: int, mip_level: int, latents: np.ndarray
    ) -> None:
        self.texture(material_id, udim_id, mip_level).from_numpy(latents)

    @property
    def type_name(self) -> str:
        return f'LatentTexture<{self.num_tiles}, {self.num_mip_levels}, {self.num_channels}>'

    def model_params(self):
        # Only latent texels are model parameters; lookup tables stay fixed.
        return [tex.buffer for tex in self.textures]

    def resolve_input_type(self, module: spy.Module):
        return 'LatentTextureInput'

    def model_data(self):
        return {
            'tile_indirection': self.tile_indirection_gpu.storage.descriptor_handle_ro,
            'material_texture_wrap': self.material_texture_wrap_gpu.storage.descriptor_handle_ro,
            'textures': [tex.get_this() for tex in self.textures],
        }

    def save_checkpoint_images(
        self,
        desc: list[str],
        folder: Path,
    ) -> list[tuple[list[str], str]]:
        """Export latent texture to disk as a series of EXR files."""

        out_files: list[tuple[list[str], str]] = []  # list of (desc, filename)

        for material_id in self.material_ids:
            for udim_id in self.udim_mapping[material_id]:
                for mip_level in range(self.num_mip_levels):
                    tex = self.texture(material_id, udim_id, mip_level)

                    out_desc = [*desc, f'material{material_id}', f'mip{mip_level}']
                    if self.has_udims[material_id]:
                        out_desc += [f'udim{udim_id}']

                    out_files += tex.save_checkpoint_images(out_desc, folder)

        return out_files

    def load_checkpoint_images(
        self,
        desc: list[str],
        folder: Path,
    ):
        load_items: list[tuple[Texture, Path]] = []

        for material_id in self.material_ids:
            for udim_id in self.udim_mapping[material_id]:
                for mip_level in range(self.num_mip_levels):
                    tex = self.texture(material_id, udim_id, mip_level)

                    out_desc = [*desc, f'material{material_id}', f'mip{mip_level}']
                    if self.has_udims[material_id]:
                        out_desc += [f'udim{udim_id}']

                    load_items.append((tex, tex.checkpoint_image_path(out_desc, folder)))

        # Read all material/UDIM/mip images together, then restore them in the
        # same order used to build ``load_items``.
        bitmaps = spy.Bitmap.read_multiple([path for _, path in load_items])
        for (tex, _), bitmap in zip(load_items, bitmaps, strict=True):
            tex.load_from_bitmap(bitmap)

    def generate_from_encoder(
        self,
        module: spy.Module,
        data_generators: DataGenerators,
        reference_materials: ReferenceMaterials,
        num_mip_levels: int,
        encoder: Encoder | None = None,
    ):
        """Run the encoder on material parameters to generate latent texture."""

        for material in reference_materials:
            for udim_id in material.udims:
                for mip_level in range(num_mip_levels):
                    if encoder is None:
                        continue

                    latents = generate_udim_from_encoder(
                        module,
                        data_generators.bsdf,
                        encoder,
                        material,
                        udim_id,
                        mip_level,
                    )
                    self.from_numpy(material.id, udim_id, mip_level, latents)


def generate_udim_from_encoder(
    module: spy.Module,
    bsdf_data_generator: FalcorBsdfDataGenerator,
    encoder: Encoder,
    material: ReferenceMaterial,
    udim_id: int,
    mip_level: int,
):
    # When generating latent textures and saving them to disk, we process
    # each UDIM at a time. This requires to query encoder inputs (material
    # parameters) for each texel in the UDIM.
    # This is conceptually straightforward, but we quickly run into memory
    # issues as GPU buffers cannot exceed 2 GB. To process larger textures,
    # e.g. at 4k resolution, we need to split the work into smaller tiles
    # and call the material data generator repeatedly.

    level_resolution = max(1, material.texture_resolution >> mip_level)
    latent_data = spy.Tensor.empty(
        module.device,
        shape=(level_resolution, level_resolution),
        dtype=f'half[{encoder.num_latents}]',
    )

    # Create shared SlangPy/falcor2 buffer for one tile, making sure it will
    # fit into the buffer size constraints.
    two_gb = 1 << 31
    element_size = encoder.num_inputs * 2  # Half-precision encoder inputs.
    # Size tiles from the half-precision encoder-input buffer. Use square
    # power-of-two subdivisions so all tiles have the same shape.
    max_element_count = two_gb / element_size
    max_tile_resolution = int(math.sqrt(max_element_count))
    tile_count_along_one_axis = 1
    tile_resolution = level_resolution
    while tile_resolution > max_tile_resolution:
        tile_count_along_one_axis *= 2
        tile_resolution //= 2
    tile_shape = (tile_resolution, tile_resolution)

    # Compute (u, v) offset for the UDIM based on its ID.
    uv_offset = udim_offset(udim_id)

    # As described above, process the UDIM in smaller tiles due to buffer
    # size constraints.
    tile_uv_extent = 1.0 / spy.float2(tile_count_along_one_axis)
    for tile_i in range(tile_count_along_one_axis):
        for tile_j in range(tile_count_along_one_axis):
            # UV range for this tile.
            tile_uv_min = uv_offset + tile_uv_extent * spy.float2(tile_i, tile_j)
            tile_uv_max = tile_uv_min + tile_uv_extent

            # Generate the UV at each texel center in this tile.
            uv = module.latent_texture_tile_uvs(
                spy.grid(tile_shape),
                spy.int2(tile_shape),
                tile_uv_min,
                tile_uv_max,
            )
            encoder_inputs = bsdf_data_generator.eval_encoder_inputs(
                material,
                mip_level,
                uv,
            )

            # Process this tile by running the encoder on the parameters,
            # and filling in the generated latent code into the texture.
            tile_offset = tile_resolution * spy.int2(tile_i, tile_j)
            module.encode_latent_texture_tile(
                latent_data,
                encoder,
                material.id,
                encoder_inputs,
                tile_offset,
                spy.call_id(),
            )

    return latent_data.to_numpy()
