// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// clang-format off
implementing neural_networks;

__include components.elu;
__include components.exp;
__include components.identity;
__include components.leaky_relu;
__include components.relu;
__include components.scaled_sigmoid;
__include components.sigmoid;
__include components.smelu;
__include components.swish;
__include components.tanh;
